### ISSUE TITLE
Gzip compression causes IllegalStateException on Android

### ISSUE THREAD

**Issue by mkneissl** [spray/spray#1005]
My route uses the  compressResponseIfRequested directive.

On Android this causes an IllegalStateException (see following stack trace).

    02-05 13:10:03.494: E/a.actor.LocalActorRef(5856): java.lang.IllegalStateException: setLevel cannot be called after setInput
    02-05 13:10:03.494: E/a.actor.LocalActorRef(5856): 	at java.util.zip.Deflater.setLevel(Deflater.java:428)
    02-05 13:10:03.494: E/a.actor.LocalActorRef(5856): 	at spray.httpx.encoding.DeflateCompressor.flush(Deflate.scala:52)
    02-05 13:10:03.494: E/a.actor.LocalActorRef(5856): 	at spray.httpx.encoding.Encoder$class.startEncoding(Encoder.scala:43)
    02-05 13:10:03.494: E/a.actor.LocalActorRef(5856): 	at spray.httpx.encoding.Gzip.startEncoding(Gzip.scala:23)

(Spray 1.3.2)

**Comment by jrudolph** [comment]
We are using kind of a hack to allow proper flushing after each chunk of input data which isn't supported in Java 6 otherwise which involves reconfiguring the deflation level during compression.

The proper way would be using the [new overload of `deflate`](https://docs.oracle.com/javase/7/docs/api/java/util/zip/Deflater.html#deflate(byte[],%20int,%20int,%20int)) added in Java 7 and for Android starting with API level 19 (Android 4.4).

I think we need some kind of configurable "flushing strategy" that would allow either to a) disable flushing (e.g. for Android pre API level 19), b) the current hack way for Java 6, or c) using the new deflate overload if available (if not otherwise possible per reflection).

**Comment by mkneissl** [comment]
Let me know if I can help (and how). Would "magic" be acceptable (using the platform name / version and / or reflection to find the most correct strategy?

**Comment by sirthias** [comment]
Moving to Akka HTTP.
I don't think this issue affect enough users to still warrant a somewhat involved fix the requires changes to the outside API in spray.

**Comment by jrudolph** [comment]
Moved to akka/akka#16810.
