### ISSUE TITLE
Forward slashes are not correctly encoded in HTTP queries

### ISSUE THREAD

**Issue by hakuch** [spray/spray#1039]
I'm using spray_2.10:1.3.2.

```scala
import spray.http.Uri

// This works as expected.
Uri.Query("foo" -> "ab+c=").toString
// res13: String = foo=ab%2Bc%3D

// Uh oh.
Uri.Query("foo" -> "ab/c=").toString
// res14: String = foo=ab/c%3D
```

I expect `'/'` to be encoded as `'%2F'`.

**Comment by jrudolph** [comment]
Slashes don't need to be encoded in the query part of a URI. See http://tools.ietf.org/html/rfc3986#section-3.4:

> The characters slash ("/") and question mark ("?") may represent data
   within the query component.   Beware that some older, erroneous
   implementations may not handle such data correctly when it is used as
   the base URI for relative references (Section 5.1), apparently
   because they fail to distinguish query data from path data when
   looking for hierarchical separators.  However, as query components
   are often used to carry identifying information in the form of
   "key=value" pairs and one frequently used value is a reference to
   another URI, it is sometimes better for usability to avoid percent-
   encoding those characters.
