### ISSUE TITLE
Migration to Akka?

### ISSUE THREAD

**Issue by aksiksi** [spray/spray#1116]
I just heard that Spray is migrating to Akka HTTP. For some odd reason, there doesn't seem to be anything about this on either the Akka or Spray websites from what I can tell.

So what _is_ going to happen to Spray? Given the commit activity, I'd assume it will be killed off. If that is the case, why don't you add a notice on the repo's `README.md` at the very least to let people know about what's happening?

On a similar note, as someone interested in using Spray in a long-term project, will it be better for me to wait out until the migration to Akka is completed, or should I use Spray directly instead? I noticed in the migration guide in the Akka HTTP docs that there are quite a few breaking changes between the two.

Thanks.

**Comment by sirthias** [comment]
There are quite a few threads on the ML regarding this topic, but you are right.
A more prominent addition to the website/documentation is probably called for.

**Comment by ktoso** [comment]
Akka HTTP has now been released as stable module ( akka.io/news/2016/11/22/akka-http-10.0.0-released.html ) thus we'll be more vocal about end-of-life of spray.

We just added a notice to the spray.io site that directs people to the akka docs etc.
For long term projects it makes sense to use Akka HTTP nowadays, esp. since it's now fully stable.

**Comment by ktoso** [comment]
Feel free to ask on https://groups.google.com/forum/#!forum/akka-user if you have any more questions!
