### ISSUE TITLE
can: add `file-based-request-entity-threshold` server config setting

### ISSUE THREAD

**Issue by sirthias** [spray/spray#479]
The idea is:
With the new HttpEntity / HttpData model we now have a way of referring to off-heap message content living in a file. We can make use of this facility by allowing spray-can to automatically save "large" incoming request entities in temp files and passing on an `HttpData.FileBytes` "pointer" to them with the request.

**Comment by sirthias** [comment]
This builds on https://github.com/spray/spray/issues/635.

**Comment by jrudolph** [comment]
The problem this ticket is trying to solve is that incoming file data may flood the Java heap. The suggestion here would be to buffer incoming data to the disk until it can be handled. 

In akka-http, backpressure seems to provide a better solution: out-of-the-box only as much data will arrive in the Java heap as the server is currently able to handle. Buffering is rarely needed because either the data should be handled in a streaming fashion directly or just streamed to a file. This will happen naturally through reactive streams combinators.

So, since we don't fix this in spray any more, this doesn't seem to be an issue any more.
