### ISSUE TITLE
+ routing: add `withRequestTimeout` directive

### ISSUE THREAD

**Issue by ryryguy** [spray/spray#892]
Changing the request timeout for a specific request programatically requires sending a special message to the responder.  A directive to handle this would be nice.  Also maybe for changing idle and timeout timeouts (though those seem less likely to come up).

See https://groups.google.com/forum/#!topic/spray-user/51ayw34PLUQ

Here is a directive I wrote as an example: 

    def withRequestTimeout(timeout: Duration) = mapInnerRoute { inner => ctx =>
      ctx.responder ! SetRequestTimeout(timeout)
      inner(ctx)
    }

**Comment by sirthias** [comment]
Since timeout (re)configuration between the layers will always come with its own set of problems we'd now propose to name this new directive `withShorterRequestTimeout` and have it implement an *additional* timeout, on top of what is configured underneath.
This way we don't need any communication between the layers and the user would have to set a long timeout underneath which gets (gradually) refined in the routing layer.
While this requires a little bit more thought and work on the part of the user it appears to be the overall cleaner solution.

**Comment by jrudolph** [comment]
Superseded by akka/akka#16819
