### ISSUE TITLE
Create a `decode` ResponseTransformer that tries all known decoders

### ISSUE THREAD

**Issue by mackler** [spray/spray#987]
Background can be found in [this post](https://groups.google.com/d/msg/spray-user/sr4y9PEOKVQ/mAki26JK2DUJ).

The point is that anyone who wants to decompress an encoded HTTP entity has either
  1. to read the `Content-encoding` header to ascertain which decoder to use; or
  1. to try all known decoders.

The title of this issue specifies the second option in deference to the above-referenced post, though the first option seems a reasonable alternative since (a) it will indicate whether the necessary decoder was absent, and (b) it avoids needlessly applying inappropriate decoders.

Either way, since every client programmer needing to decode will be implementing this behavior one way or the other, it makes sense for the library to provide this necessary behavior in order to avoid inter-programmer code duplication.

**Comment by sirthias** [comment]
I think having a response transformer that will simply try to apply all known decoders before giving up is a useful feature for the new high-level client API of akka-http.
Since we'd like to keep the spray API as stable as possible in the maintenance mode we are currently in I'm assigning this ticket to Akka HTTP.

**Comment by jrudolph** [comment]
Moved to akka/akka#16813.
