### ISSUE TITLE
More intuitive compilation exception in spray routing during marshalling Future

### ISSUE THREAD

**Issue by Morgaroth** [spray/spray#988]
Hello, 
I spent some time for lookng for a bug in marshalling Future[SomeType]

```scala
implicit val resultJsonFormat = jsonFormatX(Result.apply)

complete{
    (smartActor ? ThinkAbout(input)).mapTo[Result]
}
```

During compilation compiler complains about implicit not found

```
could not find implicit value for parameter marshaller:
spray.httpx.marshalling.ToResponseMarshaller[scala.concurrent.Future[Result]]
```

This is usually effect  of missing JsonFormat of object T, also in case of List[T], Option[T] etc
but not in case of Future, Future also need to be implicit value of type ExecutionContext in scope, and this is hard to came up with it.

And my question, is it  possible to add more verbose compiler error as it is done sometimes by implicitNotFound ?
e.g. `... implicit not found, may You miss implicit ExecutionContext in scope?`

**Comment by jrudolph** [comment]
Not sure if we can improve the situation in spray alone. This is basically a Scala compiler issue. We could try to be smart and provide fake implicit values implemented by macros that try to emit warnings when something like that happens but it may be that this will create more issues than it solved.

I'm closing this for now since there is currently nothing we can do about it in spray.
